name: 🔔 Discord Notification

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: 📂 Checkout code
        uses: actions/checkout@v4

      - name: 🔔 Send notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
          DISCORD_USERNAME: GitHub
          DISCORD_AVATAR: https://github.com/fluidicon.png
        uses: Ilshidur/action-discord@0.4.0
        with:
          args: ''