name: Notificação de Commit (Discord)

# 1. Quando o Workflow deve ser acionado?
on:
  # Aciona em qualquer 'push' (quando um ou mais commits são enviados)
  push:
    # Monitore apenas a branch principal (ajuste 'main' para o nome da sua branch, se for diferente)
    branches:
      - main 

# 2. O que o Workflow deve fazer?
jobs:
  notify:
    # Executa no ambiente Linux padrão
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Fazer checkout do código (Necessário para a maioria dos workflows, boa prática)
      - name: Checkout do Código
        uses: actions/checkout@v4

      # Passo 2: Enviar a mensagem para o Discord
      - name: Notificar o Discord sobre Novo Push
        # Usamos uma Action de terceiros popular e configuramos com nosso Secret
        uses: appleboy/discord-action@v1.0.6 
        with:
          # O URL completo do Webhook é passado para a Action através do nosso Secret
          webhook_id: ${{ secrets.DISCORD_WEBHOOK_URL }} 

          # Personaliza o autor da mensagem no Discord (opcional)
          username: '🤖 Bot de Commits CI/CD'
          color: '#36a64f' # Cor verde

          # Conteúdo formatado da mensagem (Markdown é suportado)
          message: |
            🔔 **[NOVO COMMIT]** 🔔

            **Repositório:** ${{ github.repository }}
            **Branch:** `${{ github.ref_name }}`
            **Autor:** @${{ github.actor }}

            **Mensagem:** >>> ${{ github.event.head_commit.message }}

            [Ver Commit Detalhado](${{ github.event.head_commit.url }})
